In [ ]:
import torch
import random

In [ ]:
a = torch.tensor(4)
a

tensor(4)

In [ ]:
a.ndim

0

In [ ]:
a.item()

4

In [ ]:
b = torch.tensor([1,2])
b

tensor([1, 2])

In [ ]:
b.ndim

1

In [ ]:
b.shape

torch.Size([2])

In [ ]:
c = torch.tensor([[1,2], [3,4]])
c

tensor([[1, 2],
        [3, 4]])

In [ ]:
c.ndim, c.shape

(2, torch.Size([2, 2]))

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0])
print("ID Tensor: \n", x)

y = torch.zeros(3,3)
print("2D Tensor: \n", y)

ID Tensor: 
 tensor([1., 2., 3.])
2D Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9895, 0.4062, 0.4686, 0.5364],
         [0.7311, 0.1844, 0.4096, 0.1440],
         [0.7523, 0.7895, 0.4240, 0.9371]]),
 torch.float32)

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
x=torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = torch.zeros_like(x)
y

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a = torch.tensor([9,8,7])
a+10

tensor([19, 18, 17])

In [ ]:
a*10

tensor([90, 80, 70])

In [ ]:
a*a

tensor([81, 64, 49])

In [ ]:
a**2

tensor([81, 64, 49])

In [ ]:
a/2

tensor([4.5000, 4.0000, 3.5000])

In [ ]:
a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])

print("Elemantwise addition of a and b: \n", a+b)

print('matrix multiplication of a and b:\n ', torch.matmul(a.view(2,1), b.view(1,2)))

Elemantwise addition of a and b: 
 tensor([4., 6.])
matrix multiplication of a and b:
  tensor([[3., 4.],
        [6., 8.]])


In [ ]:
t = torch.tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

print("Reshaping: \n", t.reshape(6,2))

Reshaping: 
 tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


In [ ]:
print("Resizing:\n ", t.view(2,6))

Resizing:
  tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


In [ ]:
print("Transposing:\n ", t.transpose(0,1))

Transposing:
  tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


#Building neural networks in pytoch

In [ ]:
import torch
import torch.nn as nn # To define neural network layers and models
import torch.optim as optim # Optimizer for training(like SGD, Adam etc)

In [ ]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.fc1 = nn.Linear(10,16) # first layer
    self.fc2 = nn.Linear(16,8)  # 2nd layer
    self.fc3 = nn.Linear(8,1)   # 3rd layer

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    x = torch.relu(self.fc2(x))
    x = torch.sigmoid(self.fc3(x))
    return x

#Model setup
model = NeuralNetwork()
print("Model: \n", model)

#Loss and Optimizer
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.01)

inputs = torch.randn((100,10))
targets = torch.randint(0,2,(100,1)).float()
epochs = 20

for epoch in range(epochs):
  optimizer.zero_grad()   #clear old gradients
  outputs = model(inputs)
  loss = criterion(outputs, targets)  # compute loss between prediction and target
  loss.backward()   # Backward pass: Computes gradient of loss w.r.t. weight.
  optimizer.step()  # Update weight to reduce the loss

  if (epoch+1) % 5 == 0:
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")


Model: 
 NeuralNetwork(
  (fc1): Linear(in_features=10, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=8, bias=True)
  (fc3): Linear(in_features=8, out_features=1, bias=True)
)
Epoch [5/20], Loss: 0.6791
Epoch [10/20], Loss: 0.6577
Epoch [15/20], Loss: 0.6250
Epoch [20/20], Loss: 0.5828


In [ ]:
class SimpleNet(nn.Module):
  def __init__(self):
    super(SimpleNet, self).__init__()
    self.weight = nn.Parameter(torch.randn(1, requires_grad = True))

  def forward(self, x):
    return x * self.weight

model = SimpleNet()
print("Initial model parameters: ", list(model.parameters()))

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

input_tensor = torch.tensor([2.0])
target_tensor = torch.tensor([4.0])

for epoch in range(100):
  optimizer.zero_grad
  output = model(input_tensor)
  loss = criterion(output, target_tensor)
  loss.backward()  .
  optimizer.step()

  if epoch % 10 == 0:
    print(f"Epoch {epoch}, Loss: {loss.item()}, weght: {model.weight.item()}")

print("Final Model Parameters: ", list(model.parameters()))


Initial model parameters:  [Parameter containing:
tensor([0.1260], requires_grad=True)]
Epoch 0, Loss: 14.047266006469727, weght: 0.27593469619750977
Epoch 10, Loss: 13.962164878845215, weght: 3.8789305686950684
Epoch 20, Loss: 11.446969032287598, weght: 0.13812261819839478
Epoch 30, Loss: 7.4011616706848145, weght: 3.674466371536255
Epoch 40, Loss: 3.2716012001037598, weght: 0.6661550998687744
Epoch 50, Loss: 0.5351043343544006, weght: 2.8711793422698975
Epoch 60, Loss: 0.17029821872711182, weght: 1.6711976528167725
Epoch 70, Loss: 2.307645797729492, weght: 1.7563406229019165
Epoch 80, Loss: 6.182787895202637, weght: 2.7938265800476074
Epoch 90, Loss: 10.409893035888672, weght: 0.7286398410797119
Final Model Parameters:  [Parameter containing:
tensor([3.8356], requires_grad=True)]
