In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.18.0


In [ ]:
scalar_tensor = tf.constant(5)
print(scalar_tensor)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
vector_tensor = tf.constant([1,2,3,4,5])
print(vector_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
matrix_tensor = tf.constant([[1,2], [3,4]])
print(matrix_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_3d = tf.constant([[[1,2], [3,4]], [[5,6], [6,7]]])
print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
print(tensor_3d[0])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
print(tensor_3d[0][0])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
print(tensor_3d[0][0][0])

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros([3,3])
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
ones_tensor = tf.ones([3,3])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
#Operations

add = tf.add(zeros_tensor, ones_tensor)
print(add)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
mul = tf.matmul(matrix_tensor, matrix_tensor)
mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
reshape_tensor = tf.reshape(matrix_tensor, [4,1])
reshape_tensor

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [ ]:
transpose_tensor = tf.transpose(matrix_tensor)
transpose_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>